version: "3.3"
services:
  mysqlroot:
    container_name: mysqlroot
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: root9root/achat:latest
    container_name: achatspring
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqlroot
